{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postfix.fullname" . }}-configmap
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $k, $v := .Values.postfix.templates }}
  {{ $k }}: |
{{ tpl $v $root | indent 4 }}
{{- end }}