---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postfix.fullname" . }}-configmap-postfix
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/main-cf: {{ tpl (index .Values.postfix.templates "main.cf" | toYaml) . | sha256sum }}
{{- with .Values.postfix.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
data:
{{- range $key, $value := .Values.postfix.templates }}
  {{ $key }}:
{{- $value | toYaml | indent 2 }}
{{- end }}
