{{- if .Values.daemonset.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app: {{ include "postfix.name" . }}
    chart: {{ include "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postfix.name" . }}
        chart: {{ template "postfix.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/sasl_passwd: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- with .Values.daemonset.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.daemonset.useHostNetwork }}
      hostNetwork: {{ .Values.daemonset.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 12 }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/postfix", "flush"]
        ports:
        - name: smtp
          containerPort: 25
          {{- if .Values.daemonset.hostPort }}
          hostPort: {{ .Values.daemonset.hostPort }}
          {{- end }}
          protocol: TCP
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        volumeMounts:
{{- range $k, $v := .Values.postfix.templates }}
        - name: configmap
          subPath: {{ $k }}
          mountPath: /etc/postfix/{{ $k }}
{{- end }}
        - name: secret
          subPath: sasl_passwd
          mountPath: /etc/postfix/sasl_passwd
          readOnly: true
        - name: spool
          mountPath: /var/spool/postfix
          {{- if .Values.persistence.subPath }}
          subPath: {{ .Values.persistence.subPath }}
          {{- end }}
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{- end }}
      volumes:
      - name: configmap
        configMap:
          name: {{ template "postfix.fullname" . }}-configmap
      - name: secret
        secret:
          secretName: {{ template "postfix.fullname" . }}-secret
      - name: spool
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "postfix.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end -}}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{- end }}
{{- with .Values.daemonset.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
  updateStrategy:
    type: {{ .Values.daemonset.updateStrategy }}
{{- end }}
