{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postfix.fullname" . }}
  labels:
    app: {{ include "postfix.name" . }}
    chart: {{ include "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
{{- with .Values.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "postfix.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postfix.name" . }}
        chart: {{ template "postfix.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/sasl_passwd: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- with .Values.deployment.podAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.resources }}
        resources:
{{ toYaml . | indent 12 }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/postfix", "flush"]
        ports:
        - name: smtp
          containerPort: 25
          protocol: TCP
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
        volumeMounts:

{{- range $k, $v := .Values.postfix.templates }}
        - name: configmap
          subPath: {{ $k }}
          mountPath: /etc/postfix/{{ $k }}
{{- end }}
        - name: secret
          subPath: sasl_passwd
          mountPath: /etc/postfix/sasl_passwd
          readOnly: true
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts . | indent 8 }}
{{- end }}
      volumes:
      - name: configmap
        configMap:
          name: {{ template "postfix.fullname" . }}-configmap
      - name: secret
        secret:
          secretName: {{ template "postfix.fullname" . }}-secret
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes . | indent 6 }}
{{- end }}
{{- with .Values.deployment.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}
