---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postfix.fullname" . }}-secret-postfix
  labels:
    app: {{ template "postfix.name" . }}
    chart: {{ template "postfix.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/sasl_passwd: {{ .Values.postfix.secrets.sasl_passwd | toYaml | sha256sum }}
{{- with .Values.postfix.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  sasl_passwd: {{ .Values.postfix.secrets.sasl_passwd | toYaml }}
