{{- $root := . -}}
{{- $map := fromYaml (include "argoproj-crd.namespaces" .) -}}
{{- range $namespace := $map.namespaces | uniq }}
---
apiVersion: v1
kind: Namespace
{{- with $namespace.metadata }}
metadata:
{{ toYaml . | indent 2 }}
{{- end }}
{{- with $namespace.spec }}
spec:
{{ toYaml . | indent 2 }}
{{- end }}
{{- with $namespace.status }}
status:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
