{{- if .Values.rbac.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: {{ .Release.Namespace }}
  labels:
    app: helm
    name: tiller
    chart: {{ template "tiller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "batch"
  - "extensions"
  - "apps"
  - "autoscaling"
  - "aws.chatwork"
  - "rbac.authorization.k8s.io"
  - "scheduling.k8s.io"
  - "storage.k8s.io"
  - "policy"
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller
  labels:
    app: helm
    name: tiller
    chart: {{ template "tiller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tiller
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: {{ .Release.Namespace }}
{{- end }}
