{{- if .Values.rback.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: {{ .Release.Namespace }}
  labels:
    app: helm
    name: tiller
    chart: {{ template "tiller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
  labels:
    app: helm
    name: tiller
    chart: {{ template "tiller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: {{ .Release.Namespace }}
{{- end }}
