apiVersion: v1
kind: Service
metadata:
  name: tiller-deploy
  labels:
    app: helm
    name: tiller
    chart: {{ template "tiller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: tiller
    port: 44134
    targetPort: tiller
  selector:
    app: tiller
    name: tiller
  type: ClusterIP
