# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: gcr.io/kubernetes-helm/tiller
  tag: v2.12.3
  pullPolicy: IfNotPresent

rbac:
  create: true
  name: managed-tiller
  rules:
  - apiGroups:
    - ""
    - "batch"
    - "extensions"
    - "apps"
    - "autoscaling"
    - "rbac.authorization.k8s.io"
    - "scheduling.k8s.io"
    - "storage.k8s.io"
    - "policy"
    resources: ["*"]
    verbs: ["*"]
