deployment:
  priorityClassName: system-cluster-critical
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
  env:
    - name: AWS_SHARED_CREDENTIALS_FILE
      value: /meta/aws-iam/credentials
  volumeMounts:
    - name: aws-iam-credentials
      mountPath: /meta/aws-iam
      readOnly: true
  volumes:
    - name: aws-iam-credentials
      secret:
        secretName: aws-iam-assume-role-operator-role

rbac:
  create: true
