# This is a sample file for creating a certificate with cert-manager.
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: contour-selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: contour-ca
spec:
  secretName: contour-ca-tls
  commonName: contour-ca
  #duration: 24h
  #renewBefore: 1h
  isCA: true
  issuerRef:
    name: contour-selfsigning-issuer
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: contour-ca-issuer
spec:
  ca:
    secretName: contour-ca-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: contour
spec:
  dnsNames:
  - contour
  - contour.contour.svc
  - contour.contour.svc.cluster.local
  #duration: 24h
  #renewBefore: 1h
  issuerRef:
    name: contour-ca-issuer
  secretName: contour-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: envoy
spec:
  dnsNames:
  - envoy
  - envoy.contour.svc
  - envoy.contour.svc.cluster.local
  #duration: 24h
  #renewBefore: 1h
  issuerRef:
    name: contour-ca-issuer
  secretName: envoy-tls
