apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials
  labels:
    app: {{ template "gcp-credentials.name" . }}
    chart: {{ template "gcp-credentials.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  application_default_credentials.json: {{ tpl .Values.credentialsJson . | b64enc | quote }}
