{{- if .Values.rbac.create }}
apiVersion: {{ include "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    {{- include "draino.labels" . | nindent 4 }}
  name: {{ include "draino.fullname" . }}
rules:
- apiGroups: ['']
  resources: [events]
  verbs: [create, patch, update]
- apiGroups: ['']
  resources: [nodes]
  verbs: [get, watch, list, update]
- apiGroups: ['']
  resources: [nodes/status]
  verbs: [patch]
- apiGroups: ['']
  resources: [pods]
  verbs: [get, watch, list]
- apiGroups: ['']
  resources: [pods/eviction]
  verbs: [create]
- apiGroups: [extensions]
  resources: [daemonsets]
  verbs: [get, watch, list]
{{- end }}