version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make ci:enable:k8s
      - run: make ci:enable:helm
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && ../.circleci/check-version.sh || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make apply || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make test || exit 255" || (make ci:dump && exit 1)
  publish:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:a1:e2:9e:89:f8:c2:87:7c:5a:89:bd:31:ed:88:2d"
      - run: echo -e "  StrictHostKeyChecking no\n" >> ~/.ssh/config
      - checkout
      - run: make ci:enable:helm -e HELM_CLIENT_ONLY=true
      - run: git clone -b gh-pages git@github.com:chatwork/charts.git .dist
      - run: ls -d */ | xargs -I{} helm package {} -d .dist/
      - run: helm repo index .dist/ --url https://chatwork.github.io/charts
      - run: cd .dist && git add . && git commit --allow-empty-message -m "$CIRCLE_SHA1" && git push origin gh-pages
      - run: docker login -u="${DOCKER_REGISTRY_USERNAME}" -p="${DOCKER_REGISTRY_PASSWORD}"
      - run:
          name: notification failed
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(helm inspect chart ./{} | awk '/^version:/ {print $NF}');
              make ci:notify -e TITLE="CircleCI: Failed push chatwork/charts {}:${version} (devil)" \
                             -e BODY="$(git log -1 --pretty=format:"%h - %an : %s" ${CIRCLE_BRANCH})";
            '
          when: on_fail
      - run:
          name: notification success
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(helm inspect chart ./{} | awk "/^version:/ {print $NF}");
              changelog=$(make ci:changelog -e DIR="{}/");
              make ci:notify -e TITLE="Release chatwork/charts {}:${version} (gogo)" \
                             -e BODY="$(echo -e "changelog\n${changelog}")";
            '
          when: on_success
workflows:
  version: 2
  integration:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
