version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: make ci:enable:k8s
      - run: make ci:enable:helm
      - run: make apply
      - run: make test
  "gh-pages":
    machine: true
    steps:
      - checkout
      - run: git checkout gh-pages
      - persist_to_workspace:
         root: .
         paths:
          - ./*
  "build-repo":
    docker:
      - image: dtzar/helm-kubectl:2.9.1
    steps:
      - checkout
      - run: helm init --client-only
      - attach_workspace:
          at: ./dist
      - run: ls -d */ | xargs -I{} helm package {} -d dist/
      - run: helm repo index dist/ --url https://chatwork.github.io/charts
      - persist_to_workspace:
         root: dist
         paths:
          - ./*
  "update-repo":
    docker:
      - image: buildpack-deps:jessie
    steps:
      # ~/.ssh/config
      # Host github.com
      #   IdentitiesOnly yes
      #   IdentityFile /root/.ssh/id_rsa_xxxx¥
      #   StrictHostKeyChecking no
      - add_ssh_keys:
          fingerprints:
            - "56:a1:e2:9e:89:f8:c2:87:7c:5a:89:bd:31:ed:88:2d"
      - run: echo -e "  StrictHostKeyChecking no\n" >> ~/.ssh/config
      - attach_workspace:
          at: .
      - run: git commit -a --allow-empty-message -m '' && git push origin gh-pages
workflows:
  version: 2
  integration:
    jobs:
      - test
      - gh-pages
      - "build-repo":
          requires:
            - gh-pages
      - "update-repo":
          requires:
            - test
            - build-repo
          filters:
            branches:
              only: example-charts
