# Default values for php.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: appscode/guard
  tag: 0.2.1
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""


# Arguments to be delivered to container guard.
# https://github.com/appscode/guard/blob/master/docs/reference/guard_run.md
args:
  # log level for V logs.
  verbose: 3
  # name of providers for which guard will provide authentication service.
  authProvider: "github"

# If true, runs Guard server on master instances.
runOnMaster: true

# Address of NTP serer used to check clock skew.
# http://wiki.nothing.sh/page/NTP/%BF%E4%BE%A9%B8%F8%B3%AB%A5%B5%A1%BC%A5%D0#b262580b
ntpServer: s2csntp.miz.nao.ac.jp

pki:
  # CA certificate.
  # $GUARD_DATA_DIR/pki/ca.crt
  # sample 10.96.10.96
  caCrt: |
    -----BEGIN CERTIFICATE-----
    MIICuDCCAaCgAwIBAgIBADANBgkqhkiG9w0BAQsFADANMQswCQYDVQQDEwJjYTAe
    Fw0xODEwMTgwOTMwNDBaFw0yODEwMTUwOTMwNDBaMA0xCzAJBgNVBAMTAmNhMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3Ed8DE5q+/ZMV26eFryZpdS
    oh2PrIkOBIb01KvXjTRxEYYVMDZT0sRW0fJBQBBtt8wtMOiKD6sSYrxPA2p2io9H
    DWbtCR107LM9ICrR35iqeqQh6ohKFdCXYPzfjgv0bXNCrzCu01yoW5g8OfKPd+AS
    ryG0wQQCVRaAHLw5c9uVqe0o1EyKFoj8b01J3lbqLK9tBC/N1YB4gUTLHEkOVovS
    DUV0Qk200QzIhMsEaBX8roaAox3ASmzEPPEYnJ3tmCj7olfVU5qlT2yBBweUo+xa
    ChjD/PtLOkvxRp6NMHlmf4/I29Tg9EbVxEIiaTAsUnmqnCNlJCV9ARz3miNH1wID
    AQABoyMwITAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG
    9w0BAQsFAAOCAQEAjs0wuvQCnLGdbiknCgLYcvxvPxcmL0Tmk1sYOVzf78BKu7X2
    6Hpd75knrd2VrySThf6P8B+qHXaRkA3lyhj9xwxdt47hYGcaMlzaM5qaghp8TWYG
    /iC2DxsV8EC3bcQ9c28GrXhbrCvjceH0Vi7wAyglGMJ+Rntq2AM9djSw7aSXSaRM
    6NQxY06YLtTF4fLdeIRqO/OsXY5ZEdjhMnd91HcnD3gPLRGW5J/xAMuq3Y0lLaEv
    NU7gadDaWlfDxfCvSY4LUnLouIjcD0AN15rwj+QayPBn/5PMhhVPhpZUDkBFCeNE
    yGRcqgVmwbtg6ciyN1XTPyVLV4LK366GjVNbAQ==
    -----END CERTIFICATE-----

  # Server TLS certificate.
  # $GUARD_DATA_DIR/pki/server.crt
  # sample 10.96.10.96
  tlsCrt: |
    -----BEGIN CERTIFICATE-----
    MIIDGTCCAgGgAwIBAgIJAPY+Bf6Q4i+sMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNV
    BAMTAmNhMB4XDTE4MTAxOTA1MzQzMVoXDTI4MDcxODA1MzQzMVowUTELMAkGA1UE
    BhMCSlAxDjAMBgNVBAgMBVRva3lvMRIwEAYDVQQHDAlNaW5hdG8ta3UxDTALBgNV
    BAoMBHRlc3QxDzANBgNVBAMMBnNlcnZlcjCCASIwDQYJKoZIhvcNAQEBBQADggEP
    ADCCAQoCggEBAKzzVxCmv5wP8zLCAYphjg7DDO3LlqMkPBI9X2ueDkP0PB+sUnEc
    5oxEiDQMoEDhaV4LQ7kV75M5dEl9/BQqcjFEQN9249iyECbZZdOh4p+QG9OBJVGR
    ArPcZByO0bwQFdjcgATpk6ySuwB2Dw6VYTh5BJxjmIESVJnl/+qdTNH88v7MUC3L
    oYdu+neCuni+vfZyjLoUC+Dgz7BzmFTduH7jE6hTzy1LuCF1SyyrQdPhSHq7bxwA
    BSyCw7m2Hu/MwRvlMpoYDsJkvqQSQ5rUDLgfOiQzzgi4XDnLYsFgrsymVqqOWDhJ
    5K6kLJHoJl2EIZ6ECLL6TRjI/8LUq3NH8o8CAwEAAaM4MDYwDwYDVR0RBAgwBocE
    CmAKYDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZI
    hvcNAQELBQADggEBAEGpzSY6mon7KDxuooCL1uc0FB8CIDXrChi65D5OaIR8Jab/
    h7Ub4nJ/AZYkK/saHrQH6NhbB1juddrrA8tKpdFyOWFvP6rE11lcECVLAda87u6B
    V2pFolVpgC2mG0ZWigAfplAFSKAhMl2v+eQtwlem7TKB6cyBrHJo7/srd5SV2ygv
    kyRs7CnUNkeEzdVB/X4OTua6+JRlXMPWTlIBptvJCfXR3rzyMF69JgxCVlBF5Ca5
    49gsZ1kygdiGctCWqfMvUKnVNHlMSqkMp9gM6AEmJfUulEjff6bwkzMAg7sgg7uE
    4RL9cqxr7LH6+oAO6V6STjfuh2bzcI1VTePuGls=
    -----END CERTIFICATE-----

  # Server TLS private key.
  # $GUARD_DATA_DIR/pki/server.key
  # sample 10.96.10.96
  tlsKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEArPNXEKa/nA/zMsIBimGODsMM7cuWoyQ8Ej1fa54OQ/Q8H6xS
    cRzmjESINAygQOFpXgtDuRXvkzl0SX38FCpyMURA33bj2LIQJtll06Hin5Ab04El
    UZECs9xkHI7RvBAV2NyABOmTrJK7AHYPDpVhOHkEnGOYgRJUmeX/6p1M0fzy/sxQ
    Lcuhh276d4K6eL699nKMuhQL4ODPsHOYVN24fuMTqFPPLUu4IXVLLKtB0+FIertv
    HAAFLILDubYe78zBG+UymhgOwmS+pBJDmtQMuB86JDPOCLhcOctiwWCuzKZWqo5Y
    OEnkrqQskegmXYQhnoQIsvpNGMj/wtSrc0fyjwIDAQABAoIBAQCkY8QM8sJL/6kl
    RNycAPA7PdDLMmljdiyXFbjeHOToWHzRikTueQ72oqln99xW7yrtFf3wLlaC9OiA
    dnylWlciVwLmpSYbMd1CX/92sngrPJoGZsnnBtOvzDtoHaRjglKRx7zzbmVMckfH
    P3A+Z2R6fiUQ1WX+wUKi6chf49ZB/QFY+cX+56VTN2wHD+pj6EXGqTe8gI1xPenc
    Ht2Dxmfoj/SR2wqhH/R5ackyewaF7NVdZciM+PlWeNB6ZFPsPN0mke5Yk3lXXJCG
    watZ552MMX/ZEql4eleTttvetwwyEfZHmqwPhbwBdIYW4LEsTK/CkBo7YLhQL/ay
    5ODs9YXZAoGBANqwaygmB3kvn4LNZTa9VQbp7777bCHYSB8o64UkqReO5cRM4+Ey
    xAS6uL91X+DIVOSMpJ5x6SquS7/Owy//sKAz7qQTs5b2dIYasAtM9SEJKB2uU6/M
    hxoiy4SSN4KOHUgJ3ATw0xCVig990oXwEegYVRFTuoxyUbxBHwUxHikNAoGBAMp1
    OA1aIOCwOtBHL1Lizx75Fbh8pF0cm9l09ye2kuE5Z3XwYRzKYBgQkbiaq4tBUB8o
    qrp6RZQX82I2QiUSTow6EIiv7uJUrHlwPHTOwJ9rB3NoxI+ZIc07mhyNrZjhoPYY
    WirU4X7SphWvAWDfVyzMve+3zqc4adimLyFasysLAoGBAKpvO9Q6bzCfUO2cLfmP
    bSjKQTLSt99YtDy0o3lMrQvTLnbihecIrYQSEdIFJAgHmUHV6qYhmNrOo/KErdJG
    r9zrHF17jUdmJEIvomvsOk7Y2A7pwgcMm25fF8XmPqTdJSzzoimnlpciNEsGgIAq
    LYp5DDNI0eaLYfAZwJdHRH4xAoGAQAIvZolIO8F71r2qyJnMwg4eP+WoUYfp/iZs
    vbGLXom3nCITkfapyvHyIFtGQRC1NCS3VZ2ywc+Qs0xUPUQ8cTkqYQy+ifAbV4mU
    k5mKbNx5zpMhEgVoGmrtnnlsmRk8upGYcFI9uMsAl3ptBSOXfCJ/KnsCavv6+vQP
    kowKeWECgYEAxzUg1FctulLUQ1Wbaow5U6NUolaadtBIAPU4kOcYjGC/8PFfRZIv
    rmEGx7fTlhGKDJ8ItgoNeSIHBmBPVKkOKy0NrDYtUlx/mrZF3Pm1VW8AzSSJLXNL
    VAYPj48ASfPxzh7u82NzitD+q2c8tYBdDeOZ26J5cozeONe0tvnbCdU=
    -----END RSA PRIVATE KEY-----

# TLS file location.
tlsFilesBase: "/etc/guard/pki"

# Port of guard container.
containerPort: 8443

# Annotations to add to the deployment pods.
podAnnotations: {}

# Allow the deployment to schedule on tainted nodes.
tolerations: {}

# Allow the deployment to schedule ussing affinity rules.
affinity: {}

livenessProbe:
  # The number of seconds to delay the first probe in the deployment pod's liveness prove.
  initialDelaySeconds: 25

readinessProbe:
  # The number of seconds to delay the first probe in the deployment pod's readiness prove.
  initialDelaySeconds: 25

# Deployment pod resources.
resources: {}


service:
  # Cluster IP matching server TLS.
  # The sample PKI is created to match the default `10.96.10.96`
  clusterIP: 10.96.10.96

  # Service port
  port: 443


rbac:
  # If true, create & use RBAC resources.
  create: true

  # Ignored if rbac.create is true.
  # Name of already existing service account associated with deployment
  serviceAccountName: default
