{{- $root := . -}}
{{- range $name, $tmpl := .Values.busybox.templates }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "php.fullname" $root }}-busybox-{{ $name | replace "." "-" }}
  labels: {{ include "php.labels" $root | nindent 4 }}
  {{- with $root.Values.busybox.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
data:
{{ tpl (toYaml $tmpl) $root | indent 2 }}
{{- end }}