---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "php.fullname" . }}-fpm-conf
  labels:
    app: {{ template "php.name" . }}
    chart: {{ template "php.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  php-fpm.conf:
{{- tpl (index .Values.fpm.templates "php-fpm.conf") . | toYaml | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "php.fullname" . }}-fpm-confd
  labels:
    app: {{ template "php.name" . }}
    chart: {{ template "php.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- $root := . -}}
{{- range $k, $v := (index .Values.fpm.templates "php-fpm.d") }}
  {{ $k }}:
{{- tpl $v $root | toYaml | indent 2 }}
{{- end }}
