{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "php.fullname" . }}
  labels:
    app: {{ template "php.name" . }}
    chart: {{ template "php.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- with .Values.replicaCount }}
  replicas: {{ . }}
{{- end }}
{{- with .Values.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "php.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "php.name" . }}
        chart: {{ template "php.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
{{- with .Values.busybox.templates }}
        checksum/busybox: {{ tpl (toYaml .) $root | sha256sum }}
{{- end }}
        checksum/nginx-conf: {{ tpl (index .Values.nginx.templates "nginx.conf" | toYaml) . | sha256sum }}
        checksum/nginx-confd: {{ tpl (index .Values.nginx.templates "conf.d" | toYaml) . | sha256sum }}
        checksum/fpm-conf: {{ tpl (index .Values.fpm.templates "php-fpm.conf" | toYaml) . | sha256sum }}
        checksum/fpm-confd: {{ tpl (index .Values.fpm.templates "php-fpm.d" | toYaml) . | sha256sum }}
{{- with .Values.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      initContainers:
      - name: "{{ .Chart.Name }}-{{ .Values.busybox.name }}"
        image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
        imagePullPolicy: {{ .Values.busybox.image.pullPolicy }}
        restartPolicy: Never
        command:
{{ tpl (toYaml .Values.busybox.command) $root | indent 8 }}
{{- with .Values.busybox.env }}
        env:
{{- range $k, $v := . }}
        - name: {{ $k }}
          value: {{ $v }}
{{- end }}
{{- end }}
{{- with .Values.busybox.envFrom }}
        envFrom:
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
        volumeMounts:
        - name: share
          mountPath: {{ .Values.busybox.sharedPath | default .Values.sharedPath }}
{{- with .Values.busybox.extraVolumeMounts }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
      containers:
      - name: "{{ .Chart.Name }}-{{ .Values.nginx.name }}"
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.nginx.port }}
          protocol: TCP
{{- with .Values.nginx.extraPorts }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
{{- with .Values.nginx.env }}
        env:
{{- range $k, $v := . }}
        - name: {{ $k }}
          value: {{ tpl $v $root }}
{{- end }}
{{- end }}
{{- with .Values.nginx.envFrom }}
        envFrom:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.nginx.livenessProbe }}
        livenessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.nginx.readinessProbe }}
        readinessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.nginx.resources }}
        resources:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep {{ .Values.fpm.processControlTimeout | default 0 }}; nginx -s quit; sleep 5"]
        {{- with .Values.fpm.processControlTimeout }}
        terminationGracePeriodSeconds: {{ add . 10 }}
        {{- end }}
        volumeMounts:
        - name: share
          mountPath: {{ .Values.sharedPath }}
        - name: php-fpm-sock
          mountPath: /var/run/php-fpm
        - name: nginx-conf
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        - name: nginx-confd
          mountPath: /etc/nginx/conf.d
{{- with .Values.nginx.extraVolumeMounts }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
      - name: "{{ .Chart.Name }}-{{ .Values.fpm.name }}"
        image: "{{ .Values.fpm.image.repository }}:{{ .Values.fpm.image.tag }}"
        imagePullPolicy: {{ .Values.fpm.image.pullPolicy }}
{{- with .Values.fpm.extraPorts }}
        ports:
{{- range $v := . }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
{{- end }}
{{- with .Values.fpm.env }}
        env:
{{- range $k, $v := . }}
        - name: {{ $k }}
          value: {{ $v }}
{{- end }}
{{- end }}
{{- with .Values.fpm.envFrom }}
        envFrom:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.fpm.livenessProbe }}
        livenessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.fpm.readinessProbe }}
        readinessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.fpm.resources }}
        resources:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 1; kill -QUIT 1; sleep {{ .Values.fpm.processControlTimeout | default 0 }}"]
        {{- with .Values.fpm.processControlTimeout }}
        terminationGracePeriodSeconds: {{ add . 10 }}
        {{- end }}
        volumeMounts:
        - name: share
          mountPath: {{ .Values.sharedPath }}
        - name: php-fpm-sock
          mountPath: /var/run/php-fpm
        - name: fpm-conf
          subPath: php-fpm.conf
          mountPath: /usr/local/etc/php-fpm.conf
        - name: fpm-confd
          mountPath: /usr/local/etc/php-fpm.d
{{- with .Values.fpm.extraVolumeMounts }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
      volumes:
      - name: share
        emptyDir: {}
      - name: php-fpm-sock
        emptyDir: {}
      - name: nginx-conf
        configMap:
          name: {{ template "php.fullname" . }}-nginx-conf
      - name: nginx-confd
        configMap:
          name: {{ template "php.fullname" . }}-nginx-confd
      - name: fpm-conf
        configMap:
          name: {{ template "php.fullname" . }}-fpm-conf
      - name: fpm-confd
        configMap:
          name: {{ template "php.fullname" . }}-fpm-confd
{{- with .Values.extraVolume }}
{{ tpl (toYaml .) $root | indent 6 }}
{{- end }}
{{- with .Values.imagePullSecrets}}
      imagePullSecrets:
{{ tpl (toYaml .) $root | indent 6 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ tpl (toYaml .) $root | indent 6 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ tpl (toYaml .) $root | indent 6 }}
{{- end }}
