{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "php.fullname" . }}
  labels: {{ include "php.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $root | toYaml | indent 4 }}
    {{- end }}
  {{- end }}
spec:
  backend:
    serviceName: {{ template "php.fullname" . }}
    servicePort: {{ .Values.service.port | default .Values.nginx.containerPort }}
  {{- with .Values.ingress.tls }}
  tls: {{ tpl (toYaml .) $root | nindent 4 }}
  {{- end }}
  rules:
    {{- range $k, $host := .Values.ingress.hosts }}
    - host: {{ tpl $host $root }}
      http:
        paths:
          {{- with $root.Values.ingress.preferPaths }}
          {{- tpl (toYaml .) $root | nindent 10 }}
          {{- end }}
          - path: /*
            backend:
              serviceName: {{ template "php.fullname" $root }}
              servicePort: {{ $root.Values.service.port | default $root.Values.nginx.containerPort }}
    {{- end }}
{{- end }}
