{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "php.fullname" . }}
  labels:
    app: {{ template "php.name" . }}
    chart: {{ template "php.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ template "php.fullname" . }}
    servicePort: 80
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
{{- range $k, $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
{{- with $root.Values.ingress.preferPaths }}
{{ toYaml . | indent 6 }}
{{- end }}
      - path: /*
        backend:
          serviceName: {{ template "php.fullname" $root }}
          servicePort: 80
{{- end }}
{{- end }}
