{{- $root := . -}}
{{- range $name, $secret := .Values.fpm.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "php.fullname" $root }}-fpm-{{ $name | replace "." "-" }}
  labels: {{ include "php.labels" $root | nindent 4 }}
  {{- with $root.Values.fpm.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $k, $v := $secret }}
  {{ $k }}: {{ tpl $v $root | b64enc | quote }}
  {{- end }}
{{- end }}
