apiVersion: v1
kind: Secret
metadata:
  name: regcred
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ template "docker-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ tpl .Values.dockerconfigjson . | b64enc | quote }}
