{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "guard.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "guard.fullname" . }}
{{ if .Values.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecret}}
{{end}}
{{- end }}
