apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "guard.fullname" . }}
  name: {{ template "guard.fullname" . }}
data:
  ca.crt: {{ .Values.pki.caCrt | b64enc | quote }}
  tls.crt: {{ .Values.pki.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.pki.tlsKey | b64enc | quote }}
