apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "guard.fullname" . }}
  name: {{ template "guard.fullname" . }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ template "guard.fullname" . }}
  type: ClusterIP
