# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deployment-v1-apps
{{- if .Values.deployment.enabled -}}
{{- $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slime.fullname" $root }}
{{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | tpl | indent 4 }}
{{- end }}
  labels:
    app: {{ template "slime.name" $root }}
    chart: {{ template "slime.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
{{- with .Values.deployment.labels }}
{{ toYaml .| indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "slime.name" $root }}
      release: {{ $root.Release.Name | quote }}
{{- with .Values.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  template:
    metadata:
      name: {{ include "slime.fullname" $root }}
      annotations:
{{- with .Values.deployment.pod.annotations }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
      labels:
        app: {{ template "slime.name" $root }}
        release: {{ $root.Release.Name | quote }}
{{- with .Values.deployment.pod.labels }}
{{ toYaml .| indent 8 }}
{{- end }}
    spec:
{{- with .Values.deployment.pod.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
{{ tpl (toYaml .Values.deployment.pod.container) $root | indent 6 }}
{{- end }}
{{- with .Values.deployment.pod.extraParameter }}
{{ toYaml . | indent 6 }}
{{- end }}
