# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#secret-v1-core
{{- $root := . }}
{{- range $index, $value := .Values.secrets }}
apiVersion: v1
{{- with $value.data }}
data:
{{- range $k, $v :=  $value.data }}
  {{ $k }}: {{ . | b64enc | quote }}
{{- end }}
kind: Secret
metadata:
  labels:
  app: {{ template "slime.name" $root }}
  chart: {{ template "slime.chart" $root }}
  release: {{ $root.Release.Name }}
  heritage: {{ $root.Release.Service }}
{{- range $key, $val := $value.metadata.label }}
{{- if not (regexMatch "^(app|chart|release|heritage)$" $key) }}
    {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
{{- range $key, $val := $value.metadata }}
{{- if ne $key "label" }}
{{- if regexMatch "^(string|bool|int|float64)$" (printf "%T" $val) }}
  {{ $key }}: {{ $val }}
{{- else }}
  {{ $key }}:
{{ toYaml $val | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- with $value.stringData }}
stringData:
{{ . | toYaml | indent 2 }}
{{- end }}
{{- with $value.type }}
type:
{{ . | toYaml | indent 2 }}
{{- end }}
{{- end }}
{{- end }}