{{ $root := . }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "twistlock-console.fullname" $root }}
  labels:
    app: {{ template "twistlock-console.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storage.className }}
  {{- with .Values.persistentVolumeClaim.selector }}
  selector:{{ tpl (toYaml .) $root | nindent 4 }}
  {{- end }}
