{{- if .Values.secrets }}
{{ $root := . }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "twistlock-console.fullname" $root }}
  labels:
    app: {{ template "twistlock-console.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
type: Opaque
{{- with .Values.secrets }}
data:{{ tpl (toYaml .) $root | nindent 4 }}
{{- end }}
{{- end}}
