{{ $root := . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "twistlock-console.fullname" . }}
  labels:
    app: {{ template "twistlock-console.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  {{- range $key, $value := .Values.serviceAccount.annotations }}
  annotations:
    {{ $key }}: {{ tpl $value $root | quote }}
  {{- end }}
