{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-alb-ingress-controller.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-alb-ingress-controller.name" . }}
    helm.sh/chart: {{ include "aws-alb-ingress-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- range $key, $value :=.Values.deployment.labels }}
    {{ $key }}: {{ tpl $value $root | quote }}
    {{- end }}
  {{- range $key, $value := .Values.deployment.annotations }}
  annotations:
    {{ $key }}: {{ tpl $value $root | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aws-alb-ingress-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aws-alb-ingress-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ tpl $value $root | quote }}
        {{- end }}
        {{- range $key, $value := .Values.podAnnotations }}
      annotations:
        {{ $key }}: {{ tpl $value $root | quote }}
        {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --cluster-name={{ required "specify clusterName via --set clusterName=YourClusterName" .Values.clusterName }}
        {{- with .Values.scope.ingressClass }}
        - --ingress-class={{ . }}
        {{- end }}
        {{- with .Values.scope.singleNamespace }}
        - --watch-namespace={{ default .Release.Namespace .Values.scope.watchNamespace }}
        {{- end }}
        {{- if not .Values.autoDiscoverAwsRegion }}
        - --aws-region={{ .Values.awsRegion }}
        {{- end }}
        {{- if not .Values.autoDiscoverAwsVpcID }}
        - --aws-vpc-id={{ .Values.awsVpcID }}
        {{- end }}
        {{- with .Values.extraArgs }}
{{ toYaml . | indent 8 }}
        {{- end }}
        env:
        {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: "{{ $value }}"
        {{- end }}
        {{- range $key, $value := .Values.envValueFromConfigMap }}
          - name: {{ $key }}
            valueFrom:
              configMapKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key }}
        {{- end }}
        {{- range $key, $value := .Values.envValueFromEnvSecret }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key }}
        {{- end }}
        {{- with .Values.envFromConfigmap }}
          envFrom:
            - configMapRef:
                name: {{ . }}
        {{- end }}
        {{- with .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ . }}
        {{- end }}
        ports:
        - name: health
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        {{- if .Values.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
          initialDelaySeconds: {{ add .Values.livenessProbe.initialDelaySeconds .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- with .Values.containerSecurityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts:  {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | indent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "serviceaccount.name" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
