# Default values for php.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

contour:
  nameOverride: ""
  fullnameOverride: ""

envoy:
  nameOverride: ""
  fullnameOverride: ""

deployment:
  contour:
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 50

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

    imagePullSecrets: []
    replicas: 2
    minAvailable: 1

    image:
      repository: "gcr.io/heptio-images/contour"
      tag: "v0.14.0"
      imagePullPolicy: "IfNotPresent"

    extraArgs: []

    resources:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

    port:
      healthz: 8000
      xds: 8001

    initialDelaySeconds:
      livenessProbe: 5
      readinessProbe: 5

    podAnnotations: {}
    tolerations: {}
    affinity: {}

  envoy:
    autoscaling:
      enabled: false
      minReplicas: 2
      maxReplicas: 5
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 50

    imagePullSecrets: []
    replicas: 2
    minAvailable: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1

    image:
      repository: "docker.io/envoyproxy/envoy"
      tag: "v1.11.0"
      imagePullPolicy: "IfNotPresent"

    logLevel: "info"

    extraArgs: []

    port:
      http: 8080
      https: 8443
      healthz: 8002

    resources:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"

    podAnnotations: {}
    tolerations: {}
    affinity: {}

service:
  contour:
    annotations: {}

  envoy:
    annotations: {}
      #service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-12234
      #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    type: NodePort
    port:
      http: 80
      https: 443

    nodePort:
      http: "0"
      https: "0"

rbac:
  create: true
