apiVersion: amazonaws.com/v1
kind: AWSIAMRole
metadata:
  name: {{ .Values.roleSecretName }}
  labels:
    app: {{ template "kube-aws-iam-controller-crd.name" . }}
    chart: {{ template "kube-aws-iam-controller-crd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  roleReference: {{ .Values.roleReference }}
  roleSessionDuration: {{ .Values.roleSessionDuration }}
