{{- if and .Values.persistence.enabled (not .Values.statefulset.enabled) }}
{{- if .not .Values.persistence.existingClaim }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    {{ toYaml .Values.persistence.annotations | nindent 4 }}
  labels:
    {{ include "fluentd.labels" . | nindent 4 }}
  name: {{ template "fluentd.fullname" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: "{{ . }}"
  {{- end }}
{{- end }}
{{- end }}