{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  name: {{ include "fluentd.serviceAccountName" . }}
{{- end }}
