{{- if .Values.contour.rbac.create }}
{{ $root := . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "contour.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "contour.fullname" . }}
  {{- range $key, $value := .Values.contour.rbac.serviceAccount.annotations }}
  annotations:
    {{ $key }}: {{ tpl $value $root | quote }}
  {{- end }}
{{- end }}
