{{ $root := . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "contour.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "contour.fullname" $root }}
  {{- range $key, $value := .Values.contour.service.annotations }}
  annotations:
    {{ $key }}: {{ tpl $value $root | quote }}
  {{- end }}
  name: {{ template "contour.fullname" $root }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.contour.port.xds }}
    name: xds
    protocol: TCP
    targetPort: {{ .Values.contour.port.xds }}
  selector:
    app: {{ template "contour.fullname" $root }}
