{{- if .Values.deployment.envoy.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ template "envoy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "envoy.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "envoy.fullname" . }}
  minReplicas: {{ .Values.deployment.envoy.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployment.envoy.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.deployment.envoy.autoscaling.metrics }}
{{ toYaml . | indent 2 }}
  {{- end }}
{{- end }}
