{{- if .Values.envoy.deployment.enabled }}
{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "envoy.fullname" $root }}
  labels:
    app: {{ template "envoy.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  {{- range $key, $value := .Values.envoy.deployment.annotations }}
  annotations:
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.envoy.deployment.replicas }}
  selector:
    matchLabels:
       app: {{ include "envoy.fullname" $root }}
       release: {{ .Release.Name }}
  {{- with .Values.envoy.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "envoy.fullname" $root }}
        release: {{ .Release.Name }}
      name: {{ template "envoy.fullname" $root }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.envoy.port.healthz }}"
        prometheus.io/path: "/stats/prometheus"
        {{- range $key, $value := .Values.envoy.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.envoy.envoy.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: envoy
        image: "{{ .Values.envoy.envoy.image.repository }}:{{ .Values.envoy.envoy.image.tag }}"
        imagePullPolicy: "{{ .Values.envoy.envoy.image.imagePullPolicy }}"
        command:
        - "envoy"
        args:
        - "-c"
        - "/config/envoy.json"
        - "--service-cluster $(CONTOUR_NAMESPACE)"
        - "--service-node $(ENVOY_POD_NAME)"
        - "--log-level"
        - "{{ .Values.envoy.envoy.logLevel }}"
        {{- with .Values.envoy.envoy.extraArgs }}
{{ toYaml . | indent 8 }}
        {{- end }}
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENVOY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.envoy.port.healthz }}
          {{- if .Values.envoy.livenessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.envoy.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.envoy.livenessProbe.periodSeconds}}
          {{- end }}
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.envoy.port.healthz }}
          {{- if .Values.envoy.readinessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.envoy.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.envoy.readinessProbe.periodSeconds}}
          {{- end }}
        resources:
{{ toYaml .Values.envoy.envoy.resources | indent 10 }}
        volumeMounts:
        - name: envoy-config
          mountPath: /config
        {{- with .Values.envoy.envoy.extraVolumeMounts }}
{{ toYaml . | indent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.envoy.port.http }}
          name: http
        - containerPort: {{ .Values.envoy.port.https }}
          name: https
        lifecycle:
          preStop:
            exec:
              command:
              - bash
              - -c
              - --
              - echo
              - -ne
              - "POST /healthcheck/fail HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"
              - '>/dev/tcp/localhost/9001'
      initContainers:
      - name: {{ template "contour.fullname" . }}-initconfig
        image: "{{ .Values.envoy.initContainers.image.repository }}:{{ .Values.envoy.initContainers.image.tag }}"
        imagePullPolicy: "{{ .Values.envoy.initContainers.image.imagePullPolicy }}"
        command:
        - "contour"
        args:
        - "bootstrap"
        - "/config/envoy.json"
        - "--xds-address={{ template "contour.fullname" . }}"
        - "--xds-port={{ .Values.contour.port.xds }}"
        {{- with .Values.envoy.initContainers.extraArgs }}
{{ toYaml . | indent 8 }}
        {{- end }}
        volumeMounts:
        - name: envoy-config
          mountPath: /config
        {{- with .Values.envoy.initContainers.extraVolumeMounts }}
{{ toYaml . | indent 8 }}
        {{- end }}
        env:
        - name: CONTOUR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: envoy-config
        emptyDir: {}
        {{- with .Values.envoy.extraVolumes }}
{{ toYaml . | indent 6 }}
        {{- end }}
      {{- with .Values.envoy.affinity }}
      affinity:
{{ tpl (toYaml .) $root | indent 8 }}
      {{- end }}
      {{- with .Values.envoy.tolerations }}
      tolerations:
{{ tpl (toYaml .) | indent 8 }}
      {{- end }}
{{- end }}
