{{ $root := . }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "envoy.fullname" $root }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  {{- range $key, $value := .Values.envoy.service.annotations }}
  annotations:
    {{ $key }}: {{ tpl $value $root | quote }}
  {{- end }}
  name: {{ template "envoy.fullname" $root }}
spec:
  {{- with .Values.envoy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 2 }}
  {{- end }}
  type: {{ .Values.envoy.service.type }}
{{- if and (.Values.envoy.daemonset.enabled) (.Values.envoy.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.envoy.service.externalTrafficPolicy }}"
{{- end }}
  ports:
  - port: {{ .Values.envoy.service.port.http }}
    name: http
    protocol: TCP
    targetPort: {{ .Values.envoy.port.http }}
{{- if and (eq "NodePort" .Values.envoy.service.type) .Values.envoy.service.nodePort.http }}
    nodePort: {{ .Values.envoy.service.nodePort.http }}
{{- end }}
  - port: {{ .Values.envoy.service.port.https }}
    name: https
    protocol: TCP
    targetPort: {{ .Values.envoy.port.https }}
{{- if and (eq "NodePort" .Values.envoy.service.type) .Values.envoy.service.nodePort.https }}
    nodePort: {{ .Values.envoy.service.nodePort.https }}
{{- end }}
  selector:
    app: {{ template "envoy.fullname" $root }}
