{{- if and (gt .Values.envoy.deployment.replicas 1.0) .Values.envoy.deployment.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ template "envoy.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "envoy.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "envoy.fullname" . }}
      release: {{ .Release.Name | quote }}
{{ toYaml .Values.envoy.deployment.pdb | indent 2 }}
{{- end }}
