---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/elasticsearch_yml: {{ tpl .Values.elasticsearch.config . | sha256sum }}
data:
  elasticsearch_conf: |
{{ tpl .Values.elasticsearch.config . | indent 4 }}
