# Default values for example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

configmaps:
- metadata:
    name: slime
    annotations:
      foo: bar
  data:
    slime: '₍Ꙭ̂₎'

- metadata:
    name: slime2
    annotations:
      foo: bar2
  data:
    slime2: '₍Ꙭ̂₎'

secrets:
- metadata:
    name: slime
    annotations:
      foo: bar
  data:
    slime: '₍Ꙭ̂₎'

#image:
#  name: nginx
#  repository: nginx
#  tag: latest
#  pullPolicy: Always

service:
  enabled: false
  type: LoadBalancer
  ports:
    http:
      internal: 8080
      external: 80
      protocol: TCP

deployment:
  enabled: true
  ## Pods replace strategy
  ## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  revisionHistoryLimit: 10
  # annotations:
  #   name: value
  # labels:
  #   name: value
  strategy: {}
  replicaCount: 1
  pod:
    # securityContext: {}
    ## https://github.com/uswitch/kiam
    ## https://github.com/jtblin/kube2iam
    #  iam.amazonaws.com/role: role-arn
    annotations:
      checksum/config: "{{ include (print $.Template.BasePath \"/configmap.yaml\") . | sha256sum }}"
      #checksum/secret: "{{ include (print $.Template.BasePath \"/secret.yaml\") . | sha256sum }}"
    labels: {}
    container:
    - image: k8s.gcr.io/pause:latest
      imagePullPolicy: Always
      name: pause
      resources: {}
      env:
      - name: HOGE
        value: "{{ .Values.service.type }}"
    extraParameter:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
