{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: "{{ template "kube-aws-iam-controller.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "kube-aws-iam-controller.fullname" .}}
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-aws-iam-controller.fullname" .}}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kube-aws-iam-controller.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
