{{- if .Values.daemonset.enabled }}
{{- $root := . -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    helm.sh/chart: {{ include "newrelic-php-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.newrelic.image.repository }}:{{ .Values.newrelic.image.tag }}"
          imagePullPolicy: {{ .Values.newrelic.image.pullPolicy }}
{{- with .Values.newrelic.image.command }}
          command:
{{ tpl (toYaml .) $root | indent 12 }}
{{- end }}
{{- if .Values.newrelic.socketfile.enabled }}
          volumeMounts:
            - mountPath: /tmp
              name: newrelic
{{- end }}
{{- if .Values.newrelic.socketfile.enabled }}
      volumes:
        - name: newrelic
          hostPath:
            path: /var/run/newrelic
{{- end }}
{{ end }}