{{- if .Values.newrelic.deployment.enabled }}
{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    helm.sh/chart: {{ include "newrelic-php-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.newrelic.deployment.replicaCount }}
{{- with .Values.newrelic.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: "{{ include "newrelic-php-agent.fullname" . }}"
        image: "{{ .Values.newrelic.image.repository }}:{{ .Values.newrelic.image.tag }}"
        imagePullPolicy: {{ .Values.newrelic.image.pullPolicy }}
{{- with .Values.newrelic.image.command }}
        command:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.newrelic.extraPorts }}
        ports:
{{- range $v := . }}
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- end }}
{{- with .Values.newrelic.extraEnv }}
        env:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.newrelic.extraEnvFrom }}
        envFrom:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.newrelic.livenessProbe }}
        livenessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- with .Values.newrelic.readinessProbe }}
        readinessProbe:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- if .Values.newrelic.socketfile.enabled }}
        volumeMounts:
          - mountPath: /tmp
            name: newrelic
{{- end }}
{{- with .Values.newrelic.extraVolumeMounts }}
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{- if .Values.newrelic.socketfile.enabled }}
      volumes:
        - name: newrelic
          hostPath:
            path: /var/run/newrelic
{{- end }}
{{- with .Values.newrelic.extraVolumes }}
{{ tpl (toYaml .) $root | indent 8 }}
{{- end }}
{{ end }}