{{- if .Values.newrelic.deployment.enabled }}
{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    helm.sh/chart: {{ include "newrelic-php-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.newrelic.deployment.replicaCount }}
{{- with .Values.newrelic.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: "{{ include "newrelic-php-agent.fullname" . }}"
        image: "{{ .Values.newrelic.image.repository }}:{{ .Values.newrelic.image.tag }}"
        imagePullPolicy: {{ .Values.newrelic.image.pullPolicy }}
{{- with .Values.newrelic.image.command }}
        command:
{{ tpl (toYaml .) $root | indent 10 }}
{{- end }}
{{ $use_daemon_address := isAbs .Values.newrelic.address }}
{{- if $use_daemon_address }}
        volumeMounts:
          - mountPath: /tmp
            name: newrelic
{{- else }}
        ports:
        - name: newrelic_daemon_port
          containerPort: 31339
          protocol: TCP
{{- end }}
{{- if $use_daemon_address }}
      volumes:
        - name: newrelic
          hostPath:
            path: /var/run/newrelic
{{- end }}
{{ end }}