{{- if and .Values.newrelic.deployment.enabled (not .Values.newrelic.daemonset.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "newrelic-php-agent.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    helm.sh/chart: {{ include "newrelic-php-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.newrelic.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.newrelic.service.type }}
  ports:
  - name: nw-daemon-port
    port: {{ $.Values.newrelic.port }}
    protocol: TCP
    targetPort: nw-daemon-port
  selector:
    app.kubernetes.io/name: {{ include "newrelic-php-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}