# Default values for newrelic-php-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
newrelic:
  image:
    repository: chatwork/newrelic-php-agent
    tag: 0.0.1
    pullPolicy: IfNotPresent
    command: []

  livenessProbe:
    tcpSocket:
      port: 31339
    failureThreshold: 2
    initialDelaySeconds: 10
    periodSeconds: 60

  readinessProbe:
    tcpSocket:
      port: 31339
    failureThreshold: 2
    periodSeconds: 5

  socketfile:
    enabled: true

  daemonset:
    enabled: false

  deployment:
    enabled: true
    replicaCount: 1

  extraPorts: []
  extraEnv: []
  extraEnvFrom: []
  extraVolumes: []
  extraVolumeMounts: []

  nameOverride: ""
  fullnameOverride: ""