# Default values for newrelic-php-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
newrelic:
  image:
    repository: chatwork/newrelic-php-agent
    tag: 0.0.1
    pullPolicy: IfNotPresent
    command: []

  address: /tmp/.newrelic.sock

  port: 31339

  livenessProbe:
    failureThreshold: 2
    initialDelaySeconds: 10
    periodSeconds: 60

  readinessProbe:
    failureThreshold: 2
    periodSeconds: 5

  daemonset:
    enabled: true
    extraPorts: []
    extraEnv: []
    extraEnvFrom: []
    extraVolumes: []
    extraVolumeMounts: []

  deployment:
    enabled: false
    replicaCount: 1
    extraPorts: []
    extraEnv: []
    extraEnvFrom: []
    extraVolumes: []
    extraVolumeMounts: []

  ingress:
    enabled: false

  service:
    type: ClusterIP

  nameOverride: ""
  fullnameOverride: ""