# Default values for simple-echo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: chatwork/newrelic-php-agent
  tag: latest
  pullPolicy: IfNotPresent
  command: []

nameOverride: ""
fullnameOverride: ""